version: '3'

services:

  mybunker:
    image: bunkerity/bunkerweb:1.4.8
    ports:
      - 80:8080
      - 443:8443
    # ⚠️ read this if you use local folders for volumes ⚠️
    # bunkerweb runs as an unprivileged user with UID/GID 101
    # don't forget to edit the permissions of the files and folders accordingly
    # example if you need to create a directory : mkdir folder && chown root:101 folder && chmod 770 folder
    # another example for existing folder : chown -R root:101 folder && chmod -R 770 folder
    # more info at https://docs.bunkerweb.io
    volumes:
      - bw_data:/data
      - bw_config:/etc/nginx
    environment:
      - SERVER_NAME=www.example.com
      - MULTISITE=yes
      - AUTO_LETS_ENCRYPT=yes
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
      - www.example.com_USE_UI=yes
      - www.example.com_SERVE_FILES=no
      - www.example.com_USE_REVERSE_PROXY=yes
      - www.example.com_REVERSE_PROXY_URL=/changeme                     # replace with another url
      - www.example.com_REVERSE_PROXY_HOST=http://myui:7000
      - www.example.com_REVERSE_PROXY_HEADERS=X-Script-Name /changeme   # replace with another url
      - www.example.com_REVERSE_PROXY_INTERCEPT_ERRORS=no
      - www.example.com_LIMIT_REQ_URL=/changeme/plugins/upload           # replace with another url
      - www.example.com_LIMIT_REQ_RATE=4r/s
      - www.example.com_LIMIT_REQ_URL_1=/changeme/logs                   # replace with another url
      - www.example.com_LIMIT_REQ_RATE_1=4r/s
    labels:
      - "bunkerweb.UI"
    networks:
      - net_ui
      - net_svc

  myui:
    image: bunkerity/bunkerweb-ui:1.4.8
    depends_on:
      - myuiproxy
    volumes:
      - bw_data:/data
      - bw_config:/etc/nginx
    environment:
      - ABSOLUTE_URI=https://www.example.com/changeme/                    # replace with another url
      - DOCKER_HOST=tcp://myuiproxy:2375
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=changeme                                           # replace with a stronger password
    networks:
      - net_ui
      - net_docker

  myuiproxy:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
    networks:
      - net_docker

volumes:
  bw_data:
  bw_config:


networks:
  net_ui:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  net_docker:
  net_svc:
