version: '3.6'

# clone the repository https://github.com/bigbluebutton/docker into the root directory and run the following command: ./scripts/setup
# when executing the file ./scripts/setup do this:

# Should greenlight be included? (y/n): y
# Should an automatic HTTPS Proxy be included? (y/n): n
# ...
# Please enter the domain name: www.example.com (your domain name)

# after generating your bigbluebutton docker-compose.yml file, you can modify the following to add bunkerweb to it

services:

  ...

  nginx:
    ...
    # comment this line
    # network_mode: host
    # then add the following lines
    networks:
      bbb-net:
        ipv4_address: 10.7.7.253
    ...

  ...

  mybunker:
    image: bunkerity/bunkerweb:1.4.8
    ports:
      - 80:8080
      - 443:8443
    # ⚠️ read this if you use local folders for volumes ⚠️
    # bunkerweb runs as an unprivileged user with UID/GID 101
    # don't forget to edit the permissions of the files and folders accordingly
    # example if you need to create a directory : mkdir folder && chown root:101 folder && chmod 770 folder
    # another example for existing folder : chown -R root:101 folder && chmod -R 770 folder
    # more info at https://docs.bunkerweb.io
    volumes:
      - bw_data:/data
    environment:
      - SERVER_NAME=${DOMAIN}
      - AUTO_LETS_ENCRYPT=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_WS=yes
      - REVERSE_PROXY_URL=/
      - REVERSE_PROXY_HOST=http://10.7.7.253:48087
    # You have to put this IP address in your docker-compose.yml file
    networks:
      bbb-net:
        ipv4_address: 10.7.7.254
  
  ...

volumes:
  ...
  bw_data: