version: '3'

services:

  mybunker:
    image: bunkerity/bunkerweb:1.4.8
    ports:
      - 80:8080
      - 443:8443
    # ⚠️ read this if you use local folders for volumes ⚠️
    # bunkerweb runs as an unprivileged user with UID/GID 101
    # don't forget to edit the permissions of the files and folders accordingly
    # example if you need to create a directory : mkdir folder && chown root:101 folder && chmod 770 folder
    # another example for existing folder : chown -R root:101 folder && chmod -R 770 folder
    # more info at https://docs.bunkerweb.io
    volumes:
      - bw_data:/data
    environment:
      - SERVER_NAME=www.example.com # replace with your domain
      - SERVE_FILES=no
      - DISABLE_DEFAULT_SERVER=yes
      - AUTO_LETS_ENCRYPT=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - MAX_CLIENT_SIZE=50m
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/
      - REVERSE_PROXY_HOST=http://myps
      - LIMIT_REQ_URL_1=/install/index.php
      - LIMIT_REQ_RATE_1=8r/s
      
  myps:
    image: prestashop/prestashop:1.7
    volumes:
      - ./ps-data:/var/www/html
    environment:
      - DB_SERVER=mydb
      - DB_USER=user
      - DB_PASSWD=db-user-pwd        # replace with a stronger password (must match MYSQL_PASSWORD)
      - DB_PREFIX=prefix_            # replace with a random prefix (good security practice)
      - DB_NAME=prestashop
      - PS_ENABLE_SSL=1
      - ADMIN_MAIL=admin@example.com   # change to the prestashop admin email
      - ADMIN_PASSWD=changeme          # change to the prestashop admin password
      - PS_FOLDER_ADMIN=administration # change to the prestashop admin folder

  mydb:
    image: mariadb
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db-root-pwd # replace with a stronger password
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=user
      - MYSQL_PASSWORD=db-user-pwd      # replace with a stronger password (must match DB_PASSWD)

volumes:
  bw_data: